pragma Singleton
import QtQuick

// The hypridle config axiom runs hypridle with (HypridleManager), from the
// Idle section: a general block, then one listener per step whose timeout
// isn't 0 (dim, lock, screen off, suspend) in timeout order, then the
// user's own listeners.
QtObject {
  id: root

  // `idle` is the Idle config section; `ctx` is { lockCmd, shellCommand,
  // dpmsOff, dpmsOn } (lockCmd "" leaves lock_cmd out)
  function render(idle, ctx) {
    const lines = ["# Generated by axiom from the Idle settings. Edits are overwritten.", "", "general {"];
    if (ctx.lockCmd)
      lines.push(`  lock_cmd = ${_value(ctx.lockCmd)}`);
    if (idle.lockBeforeSleep)
      lines.push("  before_sleep_cmd = loginctl lock-session");
    if (idle.screenOnAfterSleep)
      lines.push(`  after_sleep_cmd = ${_value(ctx.dpmsOn)}`);
    if (!idle.respectInhibitors) {
      lines.push("  ignore_dbus_inhibit = true");
      lines.push("  ignore_systemd_inhibit = true");
    }
    lines.push("}");

    for (const listener of listeners(idle, ctx)) {
      lines.push("", "listener {", `  timeout = ${listener.timeout}`, `  on-timeout = ${_value(listener.onTimeout)}`);
      if (listener.onResume)
        lines.push(`  on-resume = ${_value(listener.onResume)}`);
      lines.push("}");
    }
    return lines.join("\n") + "\n";
  }

  // The listeners, as { timeout, onTimeout, onResume }
  function listeners(idle, ctx) {
    const steps = [
      {
        "timeout": idle.dimTimeout,
        "onTimeout": idle.dimMode === "by" ? `${ctx.shellCommand} ipc call brightness dimBy ${idle.dimBy}` : `${ctx.shellCommand} ipc call brightness dim ${idle.dimLevel}`,
        "onResume": `${ctx.shellCommand} ipc call brightness undim`
      },
      {
        "timeout": idle.lockTimeout,
        "onTimeout": "loginctl lock-session",
        "onResume": ""
      },
      {
        "timeout": idle.screenOffTimeout,
        "onTimeout": ctx.dpmsOff,
        "onResume": ctx.dpmsOn
      },
      {
        "timeout": idle.suspendTimeout,
        "onTimeout": "systemctl suspend",
        "onResume": ""
      }
    ].map((step, index) => Object.assign(step, {
        "order": index
      })).filter(step => step.timeout > 0);
    // Steps on the same timeout keep the order above (sort isn't stable)
    steps.sort((a, b) => a.timeout - b.timeout || a.order - b.order);
    const own = (idle.listeners ?? []).filter(listener => listener.enabled && listener.timeout > 0 && (listener.onTimeout ?? "").trim() !== "").map(listener => ({
          "timeout": listener.timeout,
          "onTimeout": listener.onTimeout.trim(),
          "onResume": (listener.onResume ?? "").trim()
        }));
    return steps.map(step => ({
          "timeout": step.timeout,
          "onTimeout": step.onTimeout,
          "onResume": step.onResume
        })).concat(own);
  }

  // One line, with hyprlang's comment character escaped
  function _value(text) {
    return String(text).replace(/\n/g, " ").replace(/#/g, "##");
  }
}
