pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland

import qs.config
import qs.components.methods

/*
 * Sets Hyprland up for axiom (the Hyprland section, HyprlandConfig.mode).
 * One Lua "layer" (binds, required settings, the window look, blur,
 * monitor profiles, strips) reaches
 * Hyprland in one of three ways:
 *   detached  evaluated at runtime (hyprctl eval), again after every config
 *             reload, which drops it; binds on keys already taken are skipped
 *   included  written to $XDG_STATE_HOME/axiom/hyprland.lua, a module the
 *             user's hyprland.lua loads (includeLines)
 *   managed   written into ~/.config/hypr/hyprland.lua itself, with the
 *             Managed config, loading ~/.config/hypr/user/*.lua after it
 * Whenever the file isn't loaded (included but the lines are missing, or a
 * managed takeover refused), the runtime layer is applied instead, so axiom
 * still works, and `problem` says why.
 * The window look (HyprlandConfig.look: themed borders, axiom's shape,
 * gaps, Hyprland's blur, window opacity) and the blur behind axiom's
 * surfaces are also evaluated after every config reload in each mode, so
 * they win over the user's own config while they're on (_applyLook).
 */
Singleton {
  id: root

  readonly property string mode: HyprlandConfig.mode
  // Why the chosen mode isn't in effect, or ""
  readonly property string problem: _problem
  property string _problem: ""
  // "runtime" (detached), "loaded" (the file is in effect), "fallback"
  // (it isn't: see `problem`) or "pending" (still checking)
  readonly property string status: mode === "detached" ? "runtime" : _problem !== "" ? "fallback" : _loaded ? "loaded" : "pending"
  property bool _loaded: false
  // Configured keys the runtime layer skipped because Hyprland's config
  // already binds them
  readonly property var skippedKeys: _skippedKeys
  property var _skippedKeys: []
  // A problem belongs to the mode it was found in
  onModeChanged: {
    _problem = "";
    _loaded = false;
    _monitorConflicts = [];
  }

  readonly property string includePath: Paths.userStatePath + "hyprland.lua"
  readonly property string managedPath: Paths.hyprlandPath + "hyprland.lua"
  readonly property string userDir: Paths.hyprlandPath + "user"
  // What the user's hyprland.lua needs for the included mode
  readonly property string includeLines: `local ok, axiom = pcall(dofile, ${_lua(includePath)})\nif ok then axiom.setup() end`

  // What a hyprland.lua needs to start axiom with Hyprland, for the
  // detached and included modes (managed starts it itself). One line, marked
  // as install.sh's is, so applying it never splits a block.
  readonly property string autostartLines: `hl.on("hyprland.start", function() hl.exec_cmd(${_lua(startCommand)}) end) -- axiom`

  // The lines above as integration_hookup.py targets in the user's
  // hyprland.lua (IntegrationHookupManager's "hyprlandInclude" and
  // "hyprlandAutostart"): the include goes first, so what follows overrides
  // it, and the autostart last. Any line starting axiom counts, install.sh's
  // `qs -c axiom` included.
  readonly property var includeTarget: ({
      // I18n.tr("Load axiom's module")
      "title": "Load axiom's module",
      "file": managedPath,
      "text": includeLines,
      "place": "start",
      "comment": "--",
      "accept": "axiom\\.setup\\(",
      // I18n.tr("Adds the lines at the top, so your own settings after them win over axiom's.")
      "note": "Adds the lines at the top, so your own settings after them win over axiom's."
    })
  readonly property var autostartTarget: ({
      // I18n.tr("Start axiom")
      "title": "Start axiom",
      "file": managedPath,
      "text": autostartLines,
      "place": "end",
      "comment": "--",
      "accept": "(qs|quickshell) .*(-c +['\"]?axiom|-p +['\"]?\\S*axiom)",
      // I18n.tr("Adds the line at the end: Hyprland starts axiom with every session.")
      "note": "Adds the line at the end: Hyprland starts axiom with every session."
    })

  // How Hyprland, binds and hypridle start or call axiom
  readonly property string shellCommand: `qs -p '${Paths.axiomPath.replace(/\/$/, "")}'`
  // Starting it: -n (--no-duplicate) exits at once if axiom already runs,
  // so a second autostart line or a reloaded hyprland.lua can't start
  // another copy
  readonly property string startCommand: `${shellCommand} -n`
  readonly property string _header: "-- Generated by axiom"

  // --- The Lua layer ---

  // Actions (the schema's Hyprland.binds[].action) as IPC calls ({call} is
  // the bind's call, see _calls), with the default label and the section on
  // the Keybinds page. I18n.tr isn't used:
  // labels go to Hyprland, like the user's own bind descriptions.
  readonly property var _actions: ({
      "launcher": ["appLauncher {call}", "App launcher", "Axiom"],
      "launcherSearch": ["appLauncher search {0}", "Launcher: {0}", "Axiom"],
      "overlay": ["overlay {call}", "Overlay", "Axiom"],
      "overlayPage": ["overlay page {0}", "Overlay: {0}", "Axiom"],
      "edgeMenu": ["edgeMenu {call} {0}", "Edge menu: {0}", "Axiom"],
      "dock": ["dock {call} {0}", "Dock: {0}", "Axiom"],
      "workspaceOverview": ["workspaceOverlay {call}", "Workspace overview", "Workspace"],
      "powerMenu": ["powermenu {call}", "Power menu", "Axiom"],
      "lock": ["lockscreen lock", "Lock", "Axiom"],
      "toggleDnd": ["notifications toggleDnd", "Do not disturb", "Axiom"],
      "clearNotifications": ["notifications clear", "Clear notifications", "Axiom"],
      "idleInhibit": ["idleInhibit {call}", "Caffeine", "Axiom"],
      "nightLight": ["nightLight {call}", "Night light", "Axiom"],
      "nextWallpaper": ["wallpaper next", "Next wallpaper", "Axiom"],
      "workspaceStep": ["workspaces step {0} go", "Switch {0}", "Workspace"],
      "moveWindowStep": ["workspaces step {0} move", "Move window {0}", "Workspace"],
      "workspaceNth": ["workspaces nth {0} go", "Go to workspace {0}", "Workspace"],
      "moveWindowStepSilent": ["workspaces step {0} moveSilent", "Send window {0}", "Workspace"],
      "moveWindowNth": ["workspaces nth {0} move", "Move window to workspace {0}", "Workspace"],
      "moveWindowNthSilent": ["workspaces nth {0} moveSilent", "Send window to workspace {0}", "Workspace"],
      "volumeUp": ["audio volumeUp", "Volume up", "Media"],
      "volumeDown": ["audio volumeDown", "Volume down", "Media"],
      "toggleMute": ["audio toggleMute", "Mute", "Media"],
      "toggleMicMute": ["audio toggleMicMute", "Mute microphone", "Media"],
      "brightnessUp": ["brightness up", "Brightness up", "Media"],
      "brightnessDown": ["brightness down", "Brightness down", "Media"],
      "mediaPlayPause": ["media playPause", "Play/Pause", "Media"],
      "mediaNext": ["media next", "Next track", "Media"],
      "mediaPrevious": ["media previous", "Previous track", "Media"],
      "mediaStop": ["media stop", "Stop", "Media"],
      "screenshot": ["screenshot take {0}", "Screenshot: {0}", "Apps"],
      "screenRecord": ["screenRecord {call}", "Screen recording", "Apps"]
    })

  // The IPC function behind each call ({call} above) for actions that open
  // and close something; a toggle is always `toggle`
  readonly property var _calls: ({
      "launcher": {
        "open": "open",
        "close": "close"
      },
      "overlay": {
        "open": "open",
        "close": "close"
      },
      "edgeMenu": {
        "open": "open",
        "close": "close"
      },
      "dock": {
        "open": "open",
        "close": "close"
      },
      "powerMenu": {
        "open": "open",
        "close": "close"
      },
      "workspaceOverview": {
        "open": "show",
        "close": "hide"
      },
      "idleInhibit": {
        "open": "enable",
        "close": "disable"
      },
      "nightLight": {
        "open": "enable",
        "close": "disable"
      },
      "screenRecord": {
        "open": "enable",
        "close": "disable"
      }
    })

  // Whether an action takes a call (toggle, open or close)
  function hasCalls(action) {
    return _calls[action] !== undefined;
  }

  // A bind's call, "toggle" unless its action has the one it names
  function callOf(bind) {
    return _calls[bind.action]?.[bind.call] !== undefined ? bind.call : "toggle";
  }

  // Actions that are Hyprland dispatchers, bound directly: the dispatcher's
  // Lua (from the argument), the default label and the section
  readonly property var _dispatchers: ({
      "focusDir": [arg => `hl.dsp.focus({ direction = ${_lua(arg)} })`, "Focus {0}", "Window"],
      "moveWindowDir": [arg => `hl.dsp.window.move({ direction = ${_lua(arg)} })`, "Move {0}", "Window"],
      "resizeWindow": [arg => {
          const [x, y] = arg.split(/[\s,]+/).map(Number);
          return isFinite(x) && isFinite(y) ? `hl.dsp.window.resize({ x = ${x}, y = ${y}, relative = true })` : "";
        }, "Resize by {0}", "Window"],
      "closeWindow": [() => "hl.dsp.window.close()", "Close", "Window"],
      "fullscreen": [() => "hl.dsp.window.fullscreen()", "Fullscreen", "Window"],
      "toggleFloat": [() => `hl.dsp.window.float({ action = "toggle" })`, "Toggle floating", "Window"],
      "pin": [() => "hl.dsp.window.pin()", "Pin", "Window"],
      "centerWindow": [() => "hl.dsp.window.center()", "Center", "Window"],
      "toggleGroup": [() => "hl.dsp.group.toggle()", "Toggle group", "Window"],
      "pseudo": [() => "hl.dsp.window.pseudo()", "Pseudotile", "Window"],
      "toggleSplit": [() => `hl.dsp.layout("togglesplit")`, "Toggle split", "Window"],
      // Strips (the scrolling layout): the column before (left, up) or
      // after (right, down) swaps with the focused one; widths step through
      // scrolling.explicit_column_widths
      "stripSwapColumn": [arg => `hl.dsp.layout(${_lua("swapcol " + (arg === "left" || arg === "up" ? "l" : "r"))})`, "Swap column {0}", "Window"],
      "stripWider": [() => `hl.dsp.layout("colresize +conf")`, "Widen column", "Window"],
      "stripNarrower": [() => `hl.dsp.layout("colresize -conf")`, "Narrow column", "Window"],
      "stripFit": [() => `hl.dsp.layout("fit visible")`, "Fit visible columns", "Window"],
      // Any dispatcher, as Lua (`hl.dsp.layout("swapsplit")`), compiled
      // when the bind is made so a mistake only leaves that bind doing
      // nothing instead of breaking the whole file
      "lua": [arg => `(function() local ok, d = pcall(load(${_lua("return " + arg)}) or error) if ok and d then return d end return hl.dsp.no_op() end)()`, "{0}", "Custom"],
      // Lua functions entering the switcher's submap (HyprLua.switcherLua)
      "windowSwitcher": [() => HyprLua.switcherBindLua(switcherSteps.windowSwitcher), "Switch windows", "Window"],
      "windowSwitcherReverse": [() => HyprLua.switcherBindLua(switcherSteps.windowSwitcherReverse), "Switch windows backwards", "Window"],
      // On a mouse button (SUPER + mouse:272), which Hyprland makes a
      // mouse bind by itself
      "mouseDrag": [() => "hl.dsp.window.drag()", "Drag", "Window"],
      "mouseResize": [() => "hl.dsp.window.resize()", "Resize", "Window"],
      "toggleSpecial": [arg => `hl.dsp.workspace.toggle_special(${_lua(arg)})`, "Toggle {0}", "Special"],
      "moveToSpecial": [arg => `hl.dsp.window.move({ workspace = ${_lua("special:" + arg)} })`, "Move window to {0}", "Special"],
      // Run by Hyprland, not over IPC, so it works when the shell is stuck
      "restartShell": [() => `hl.dsp.exec_cmd(${_lua(`qs kill ${shellCommand.slice(3)}; ${shellCommand} -d`)})`, "Restart shell", "Axiom"],
      "exitHyprland": [() => `hl.dsp.exec_cmd(${_lua("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")})`, "Exit Hyprland", "Axiom"],
      // The apps from the Apps settings, so a bind follows them
      "terminal": [() => `hl.dsp.exec_cmd(${_lua(Apps.terminalCommand)})`, "Terminal", "Apps"],
      "fileManager": [() => `hl.dsp.exec_cmd(${_lua(Apps.fileManagerCommand)})`, "File manager", "Apps"],
      "browser": [() => `hl.dsp.exec_cmd(${_lua(Apps.browserCommand)})`, "Browser", "Apps"]
    })

  // Flags an action starts with when it's picked (the bind can change them)
  readonly property var actionFlags: ({
      "resizeWindow": ["repeating"],
      "restartShell": ["release"],
      "exitHyprland": ["release"],
      "volumeUp": ["locked", "repeating"],
      "volumeDown": ["locked", "repeating"],
      "toggleMute": ["locked"],
      "toggleMicMute": ["locked"],
      "brightnessUp": ["locked", "repeating"],
      "brightnessDown": ["locked", "repeating"],
      "mediaPlayPause": ["locked"],
      "mediaNext": ["locked"],
      "mediaPrevious": ["locked"],
      "mediaStop": ["locked"]
    })
  readonly property var flagNames: ["repeating", "locked", "release"]

  // The window switcher's actions, by the step each takes through the
  // windows (also how a bind is known to be one)
  readonly property var switcherSteps: ({
      "windowSwitcher": 1,
      "windowSwitcherReverse": -1
    })

  // The section a bind's action files it under on the Keybinds page
  function sectionFor(action) {
    return _actions[action]?.[2] ?? _dispatchers[action]?.[2] ?? "Axiom";
  }

  // The label a bind gets when its description is empty
  function defaultLabel(bind) {
    const argument = String(bind.argument ?? "").trim();
    if (bind.action === "exec")
      return argument;
    const label = (_actions[bind.action]?.[1] ?? _dispatchers[bind.action]?.[1] ?? "").replace("{0}", argument);
    const call = callOf(bind);
    return call === "toggle" ? label : `${label} (${call})`;
  }

  // Whether a description names its own section ("Section: Label")
  function hasOwnSection(description) {
    return /^[^:]+: \S/.test(String(description ?? "").trim());
  }

  // The description Hyprland gets: "Section: Label", the section from the
  // action unless the description names its own
  function descriptionFor(bind) {
    const own = String(bind.description ?? "").trim();
    return hasOwnSection(own) ? own : sectionFor(bind.action) + ": " + (own || defaultLabel(bind));
  }

  // A Lua string literal
  function _lua(text) {
    return HyprLua.string(text);
  }

  // A single-quoted shell word
  function _shellWord(text) {
    return "'" + String(text).replace(/'/g, "'\\''") + "'";
  }

  function _hex(color) {
    return [color.r, color.g, color.b].map(v => Math.round(v * 255).toString(16).padStart(2, "0")).join("");
  }

  // The hl.bind() line for a configured bind, or "" when it's incomplete
  function _bindLua(bind) {
    const argument = String(bind.argument ?? "").trim();
    if (!String(bind.key ?? "").trim() || (_needsArgument(bind.action) && !argument))
      return "";
    let dispatcher;
    if (_dispatchers[bind.action]) {
      dispatcher = _dispatchers[bind.action][0](argument);
    } else if (bind.action === "exec") {
      dispatcher = `hl.dsp.exec_cmd(${_lua(argument)})`;
    } else if (_actions[bind.action]) {
      const call = _calls[bind.action]?.[callOf(bind)] ?? "toggle";
      const ipc = _actions[bind.action][0].replace("{call}", call).replace("{0}", _shellWord(argument));
      dispatcher = `hl.dsp.exec_cmd(${_lua(`${shellCommand} ipc call ${ipc}`)})`;
    }
    if (!dispatcher)
      return "";
    const options = [`description = ${_lua(descriptionFor(bind))}`];
    for (const flag of flagNames)
      if (bind[flag])
        options.push(`${flag} = true`);
    return `hl.bind(${_lua(bind.key.trim())}, ${dispatcher}, { ${options.join(", ")} })`;
  }

  // Whether a configured bind has everything it needs to be bound
  function isComplete(bind) {
    return _bindLua(bind) !== "";
  }

  // The window switcher's submap for the switcher binds among `binds`
  function _switcherLua(binds) {
    const entries = binds.filter(bind => switcherSteps[bind.action] !== undefined && _bindLua(bind) !== "").map(bind => Object.assign(KeyNames.split(bind.key), {
        "step": switcherSteps[bind.action]
      }));
    return HyprLua.switcherLua(entries);
  }

  function _needsArgument(action) {
    return action === "exec" || (_actions[action]?.[0] ?? _dispatchers[action]?.[1] ?? "").includes("{0}");
  }

  function _requiredLua(withAnimation) {
    // The maximize rule is Hyprland's example config's, which managed mode replaces:
    // without it apps like kitty (remember_window_size) reopen maximized
    const lines = ["hl.config({ misc = { allow_session_lock_restore = true } })", `hl.window_rule({ name = "axiom-suppress-maximize", match = { class = ".*" }, suppress_event = "maximize" })`];
    if (withAnimation)
      lines.push(`hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "default", style = "slide" })`);
    return lines;
  }

  // Whether axiom's surfaces blur: as saved for a file, and at runtime as
  // now (BlurManager.active, paused over a fullscreen window), evaluated
  // over the file after every reload
  function _surfacesBlur(forFile) {
    return forFile === true ? Appearance.blur : BlurManager.active;
  }

  function _lookLua(forFile) {
    return HyprLua.lookLua(HyprlandConfig.look, ConfigManager.configSchema?.properties?.Hyprland?.properties?.look, _hex(Theme.borderFocus), _hex(Theme.border), Appearance.borderWidth, Appearance.borderRadius, _surfacesBlur(forFile));
  }

  // The blur behind axiom's surfaces, its rules written on or off
  // (HyprLua.blurLua)
  function _blurLua(forFile) {
    return HyprLua.blurLua({
      "on": _surfacesBlur(forFile),
      "threshold": Appearance.blurThreshold,
      "throughWindows": Appearance.blurThroughWindows,
      "backdrops": Appearance.blurBackdrops
    });
  }

  function _indent(lines, prefix) {
    return lines.map(line => line === "" ? "" : prefix + line).join("\n");
  }

  function _stripsLua() {
    return HyprLua.stripsLua(WorkspacesConfig.strips, ConfigManager.configSchema?.properties?.Workspaces, WorkspacesConfig.stripOptions);
  }

  // The included file: a module whose setup() applies what's enabled
  function moduleLua() {
    const binds = HyprlandConfig.binds.map(bind => _bindLua(bind)).filter(line => line !== "").concat(_switcherLua(HyprlandConfig.binds));
    const setup = [];
    if (HyprlandConfig.requiredSettings)
      setup.push("M.required()");
    setup.push("M.binds()");
    setup.push("M.look()");
    setup.push("M.blur()");
    setup.push("M.layers()");
    setup.push("M.monitors()");
    setup.push("M.strips()");
    return `${_header} from its Hyprland settings, and rewritten whenever they
-- (or the theme) change: edit those, not this file.
--
-- Load it near the top of hyprland.lua, so what follows overrides it:
--   ${includeLines.replace("\n", "\n--   ")}
-- setup() applies everything enabled in axiom's settings; call the parts
-- instead to pick. hl.unbind("KEY") after it frees one of axiom's keys.
local M = {}

-- Session lock restore, ignoring apps' maximize requests and a workspaces
-- animation (axiom's grid slides)
function M.required()
${_indent(_requiredLua(true), "  ")}
end

function M.binds()
${_indent(binds, "  ")}
end

-- Window borders in the axiom theme, its shape, gaps, Hyprland's blur and
-- window opacity, as enabled. axiom applies them again after every reload,
-- so they win over what follows while they're on.
function M.look()
${_indent(_lookLua(true), "  ")}
end
-- Its old name
M.theme = M.look

-- Blur behind axiom's surfaces while they're translucent (on or off, so
-- turning it off takes it back), at Hyprland's blur
function M.blur()
${_indent(_blurLua(true), "  ")}
end

-- Stacking order of axiom's surfaces (bars, border, edge menus, backdrops)
function M.layers()
${_indent(HyprlandManager.layerRulesLua, "  ")}
end

-- Monitor profiles from the Monitors page: the one for what's connected,
-- again whenever a monitor comes or goes
function M.monitors()
${_indent(HyprLua.monitorsLua(HyprlandConfig.monitorProfiles), "  ")}
end

-- Strips (the scrolling layout) on the monitors Workspaces lists
function M.strips()
${_indent(_stripsLua(), "  ")}
end

function M.setup()
${_indent(setup, "  ")}
end

-- Lets axiom see that this file is loaded
AXIOM_INCLUDED = true

return M
`;
  }

  function _cursorLua(m) {
    if (!m.cursorTheme)
      return "";
    return `hl.env("XCURSOR_THEME", ${_lua(m.cursorTheme)})\nhl.env("XCURSOR_SIZE", ${_lua(String(m.cursorSize))})\n`;
  }

  // What the managed file runs once Hyprland has started: the cursor,
  // axiom, then the autostart commands. A plain `hypridle` is left out
  // while axiom runs its own (Idle.enabled), and a polkit agent while axiom
  // is the agent (PolkitConfig.enabled).
  function _startLua(m) {
    const lines = [];
    if (m.cursorTheme)
      lines.push(`hl.exec_cmd(${_lua(`hyprctl setcursor ${_shellWord(m.cursorTheme)} ${m.cursorSize}`)})`);
    lines.push(`hl.exec_cmd(${_lua(startCommand)})`);
    for (const entry of m.autostart)
      if (entry.enabled && entry.command.trim() !== "" && !(Idle.enabled && entry.command.trim() === "hypridle") && !(PolkitConfig.enabled && PolkitAgents.isAgentCommand(entry.command)))
        lines.push(`hl.exec_cmd(${_lua(entry.command.trim())})`);
    return lines;
  }

  // The recommended environment (HyprLua.recommendedEnv), then the user's,
  // which wins over it
  function _envLua(m) {
    const recommended = m.recommendedEnv ? HyprLua.recommendedEnv.map(([name, value]) => ({
          "name": name,
          "value": value
        })) : [];
    return recommended.concat(m.env).filter(entry => /^[A-Za-z_][A-Za-z0-9_]*$/.test(entry.name.trim())).map(entry => `hl.env(${_lua(entry.name.trim())}, ${_lua(entry.value)})\n`).join("");
  }

  // Animation presets: curves { name: [x1, y1, x2, y2] } and leaves
  // [leaf, speed (Hyprland's unit: 100 ms), curve, style]
  readonly property var _animationPresets: ({
      "snappy": {
        "curves": {
          "axiomSnappy": [0.2, 0, 0, 1]
        },
        "leaves": [["windows", 2, "axiomSnappy", "popin 90%"], ["layers", 2, "axiomSnappy", "fade"], ["fade", 2, "axiomSnappy", ""], ["border", 1, "axiomSnappy", ""], ["workspaces", 2.5, "axiomSnappy", "slide"], ["specialWorkspace", 2.5, "axiomSnappy", "slidevert"]]
      },
      "bouncy": {
        "curves": {
          "axiomSnappy": [0.2, 0, 0, 1],
          "axiomOvershoot": [0.34, 1.56, 0.64, 1]
        },
        "leaves": [["windows", 4, "axiomOvershoot", "popin 60%"], ["windowsOut", 3, "axiomSnappy", "popin 80%"], ["layers", 3, "axiomOvershoot", "fade"], ["fade", 3, "axiomSnappy", ""], ["border", 2, "axiomSnappy", ""], ["workspaces", 4, "axiomOvershoot", "slide"], ["specialWorkspace", 4, "axiomOvershoot", "slidevert"]]
      },
      // Windows in and out almost at once, bouncing in, workspaces fading
      "lightning": {
        "curves": {
          "lightningSlow": [0, 0.85, 0.3, 1],
          "lightningOut": [0.3, -0.3, 0, 1],
          "lightningWind": [0.05, 0.9, 0.1, 1],
          "lightningOvershot": [0.7, 0.6, 0.1, 1.1],
          "lightningBounce": [1.1, 1.6, 0.1, 0.85],
          "lightningDecel": [0.05, 0.7, 0.1, 1]
        },
        "leaves": [["windowsIn", 0.5, "lightningSlow", "popin"], ["windowsOut", 0.5, "lightningOut", "popin"], ["windowsMove", 0.7, "lightningWind", "slide"], ["fade", 2, "lightningOvershot", ""], ["workspaces", 2.5, "lightningWind", "fade"], ["windows", 2, "lightningBounce", "popin"], ["specialWorkspace", 0.8, "lightningDecel", "slidevert"]]
      }
    })

  // The preset (or custom list) as { curves, leaves }, or null for
  // Hyprland's own animations
  function _animationSet(m) {
    switch (m.animationPreset) {
    case "axiom":
      {
        // Look & Feel → Motion: the shell's durations, in Hyprland's unit
        const speed = ms => Math.max(0.1, ms / 100);
        return {
          "curves": {
            "axiomMotion": [0.05, 0.7, 0.1, 1]
          },
          "leaves": [["windows", speed(Appearance.animSlow), "axiomMotion", "popin 80%"], ["layers", speed(Appearance.animNormal), "axiomMotion", "fade"], ["fade", speed(Appearance.animNormal), "axiomMotion", ""], ["border", speed(Appearance.animFast), "axiomMotion", ""], ["workspaces", speed(Appearance.animSlow), "axiomMotion", "slide"], ["specialWorkspace", speed(Appearance.animSlow), "axiomMotion", "slidevert"]]
        };
      }
    case "custom":
      {
        const curves = {};
        for (const curve of m.curves) {
          const points = curve.points.split(",").map(Number);
          if (curve.name.trim() !== "" && points.length === 4 && points.every(isFinite))
            curves[curve.name.trim()] = points;
        }
        return {
          "curves": curves,
          "leaves": m.customAnimations.map(a => [a.leaf, a.enabled ? a.durationMs / 100 : 0, a.curve.trim() || "default", a.style.trim()])
        };
      }
    }
    return _animationPresets[m.animationPreset] ?? null;
  }

  function _animationsLua(m) {
    // Following axiom's motion while it's off: animations are off (_configLua)
    const off = !m.animations || (m.animationPreset === "axiom" && !Appearance.animations);
    const set = off ? null : _animationSet(m);
    if (!set)
      return "";
    const lines = Object.keys(set.curves).map(name => {
      const p = set.curves[name].map(v => HyprLua.value(v));
      return `hl.curve(${_lua(name)}, { type = "bezier", points = { { ${p[0]}, ${p[1]} }, { ${p[2]}, ${p[3]} } } })`;
    });
    for (const [leaf, speed, curve, style] of set.leaves) {
      const parts = [`leaf = ${_lua(leaf)}`, `enabled = ${speed > 0}`];
      if (speed > 0)
        parts.push(`speed = ${HyprLua.value(speed)}`, `bezier = ${_lua(curve)}`);
      if (speed > 0 && style !== "")
        parts.push(`style = ${_lua(style)}`);
      lines.push(`hl.animation({ ${parts.join(", ")} })`);
    }
    return "\n" + lines.join("\n") + "\n";
  }

  // The managed settings as one hl.config() table
  function _configLua(m) {
    // The window look sets them when it matches axiom's shape (M.look())
    const overrides = HyprlandConfig.look.shape ? {} : {
      "decoration.rounding": m.rounding,
      "general.border_size": m.borderSize
    };
    // Following axiom's motion includes turning animations off with it
    if (m.animationPreset === "axiom" && !Appearance.animations)
      overrides["animations.enabled"] = false;
    const schema = ConfigManager.configSchema?.properties?.Hyprland?.properties?.managed;
    return `hl.config(${HyprLua.serialize(HyprLua.configTable(schema, m, name => _hex(Theme.resolveColor(name)), overrides))})`;
  }

  // The managed hyprland.lua
  function managedLua() {
    const m = HyprlandConfig.managed;
    const module = moduleLua().split("\n").filter(line => !line.startsWith("--")).join("\n").trim();
    return `${_header} (Hyprland mode: managed) from its Hyprland settings,
-- and rewritten whenever they (or the theme) change: edit those, not this file.
-- Your own config goes in ${userDir}/*.lua, loaded after this in name
-- order, so it overrides it. hl.unbind("KEY") there frees one of axiom's keys.

local axiom = (function()
${_indent(module.split("\n"), "  ")}
end)()

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
${_envLua(m)}
${_configLua(m)}
${_cursorLua(m)}
axiom.setup()
${_animationsLua(m)}
hl.on("hyprland.start", function()
${_indent(_startLua(m), "  ")}
end)

${_userFilesLua()}
`;
  }

  // Loads user/*.lua in name order: the end of managedLua() and of
  // releasedLua()
  function _userFilesLua() {
    return `-- Your files, through require (as user.<name>) so Hyprland reloads when
-- one changes. Shared modules go in user/lib/ (require("user.lib.x")),
-- which isn't loaded here. A failing file doesn't stop the rest; the
-- errors are raised together at the end (hyprctl configerrors).
local errors = {}
local files = io.popen("cd " .. ${_lua(_shellWord(userDir))} .. " 2>/dev/null && ls -1 *.lua 2>/dev/null")
if files then
  for file in files:lines() do
    local ok, err = pcall(require, "user." .. file:gsub("%.lua$", ""))
    if not ok then errors[#errors + 1] = tostring(err) end
  end
  files:close()
end
if #errors > 0 then error(table.concat(errors, "\\n")) end`;
  }

  // The hyprland.lua leaving managed gives back when the takeover set
  // nothing aside (claim_hyprland.sh release): the user's from then on,
  // starting axiom (and loading its module in included mode) and loading
  // user/*.lua as the managed one did
  function releasedLua() {
    return `-- Given back by axiom when it stopped managing Hyprland: this file is yours
-- now, and axiom won't write it again. It starts axiom and loads
-- ${userDir}/*.lua, as axiom's managed one did.
${mode === "included" ? includeLines + "\n" : ""}${autostartLines}

-- Not when it's required as one of those files itself (a managed takeover
-- adopts it into user/): the file requiring it loads them
if select("#", ...) == 0 then
${_indent(_userFilesLua().split("\n"), "  ")}
end`;
  }

  // --- Runtime (detached, and the fallback) ---

  // Keys this layer bound at runtime live in Hyprland's Lua state
  // (AXIOM_RUNTIME_KEYS), which a config reload resets along with the
  // binds, and which outlives a reload of the shell. They're unbound
  // before the binds are read, so they don't look like the user's.
  readonly property string _unbindLua: "for _, key in ipairs(AXIOM_RUNTIME_KEYS or {}) do hl.unbind(key) end\nAXIOM_RUNTIME_KEYS = nil"
  // The monitor profiles (JSON) the runtime layer last applied
  property var _monitorsApplied: null
  // Keys skipped as taken, so each is only reported once
  property var _reportedTaken: ({})
  property bool _runtimeWanted: false

  function _applyRuntime() {
    _runtimeWanted = true;
    if (!unbindRuntime.running && !getBinds.running && !getAnimations.running) {
      _runtimeReloads = _reloads;
      unbindRuntime.running = true;
    }
  }

  // Hyprland config reloads seen, and how many there were when the runtime
  // layer last started reading Hyprland's binds: one in between makes what
  // it read stale (taken keys from another config, or none at all while
  // hyprland.lua was being replaced), and binding from it would leave
  // AXIOM_RUNTIME_KEYS naming the loaded config's own keys, which
  // _clearRuntime would then unbind
  property int _reloads: 0
  property int _runtimeReloads: 0

  function _clearRuntime() {
    _runtimeWanted = false;
    _monitorsApplied = null;
    _skippedKeys = [];
    HyprlandManager.runLua(_unbindLua);
    KeybindManager.refreshSoon();
  }

  function _finishRuntime(bindList, animations) {
    if (!_runtimeWanted)
      return;
    if (_runtimeReloads !== _reloads) {
      _runtimeReloads = _reloads;
      unbindRuntime.running = true;
      return;
    }
    const plan = HyprBinds.runtimeBinds(HyprlandConfig.binds.filter(bind => _bindLua(bind) !== ""), bindList);
    for (const key of plan.unreadable)
      console.warn(`[HyprlandConfigManager] Can't read the key "${key}"; bind it as MODS + KEY`);
    for (const key of plan.skipped) {
      const id = HyprBinds.keyId(key);
      if (!_reportedTaken[id])
        console.log(`[HyprlandConfigManager] ${key} is bound by your Hyprland config; skipping axiom's bind`);
      _reportedTaken[id] = true;
    }
    const lines = plan.apply.map(bind => _bindLua(bind)).concat(_switcherLua(plan.apply));
    const keys = plan.apply.map(bind => bind.key.trim());
    const skipped = plan.skipped;
    if (HyprlandConfig.requiredSettings) {
      const anim = (Array.isArray(animations?.[0]) ? animations[0] : []).find(a => a.name === "workspaces");
      lines.push(..._requiredLua(!anim?.overridden));
    }
    lines.push(..._lookLua(false));
    _lookState.applied = HyprLua.lookParts(HyprlandConfig.look).join(",");
    lines.push(..._blurLua(false));
    // Monitors only when their profiles changed, or a reload dropped them:
    // re-applying them unchanged could still flicker a mode set
    if (_monitorsApplied !== HyprlandConfig._monitorsJson) {
      lines.push(...HyprLua.monitorsLua(HyprlandConfig.monitorProfiles));
      _monitorsApplied = HyprlandConfig._monitorsJson;
    }
    // Strips once per Hyprland load (HyprLua.stripsRuntimeLua)
    lines.push(...HyprLua.stripsRuntimeLua(_stripsLua(), WorkspacesConfig._stripsJson));
    lines.push(`AXIOM_RUNTIME_KEYS = { ${keys.map(key => _lua(key)).join(", ")} }`);
    _skippedKeys = skipped;
    HyprlandManager.runLua(lines.join("\n"));
    HyprlandManager.refreshOptions();
    KeybindManager.refreshSoon();
  }

  // --- Files (included, managed) ---

  // Writes `text` to `path` unless it's already there; then reloads
  // Hyprland, since it doesn't watch files a config loads
  function _writeIfChanged(path, text) {
    if (FileManager.read(path) === text) {
      _checkLoaded();
      return;
    }
    root._pendingWrite = {
      "path": path,
      "text": text
    };
    makeDir.command = ["mkdir", "-p", path.replace(/\/[^/]*$/, "")];
    makeDir.running = true;
  }

  property var _pendingWrite: null

  Process {
    id: makeDir
    onExited: code => {
      const write = root._pendingWrite;
      root._pendingWrite = null;
      if (code !== 0 || !write) {
        console.warn("[HyprlandConfigManager] Could not create the folder for", write?.path);
        return;
      }
      root._writeFile(writer, write.path, write.text);
    }
  }

  // After a (re)load: is the file in effect? If not, the runtime layer
  // stands in for it
  function _checkLoaded() {
    if (!checkLoaded.running)
      checkLoaded.running = true;
  }

  function _warnOnce(message) {
    if (_problem === message)
      return;
    _problem = message;
    console.warn("[HyprlandConfigManager]", message);
  }

  // --- For the settings page ---

  // Managed mode: the user/*.lua files that set monitors themselves. They
  // load after axiom's profiles, so their rules win.
  readonly property var monitorConflicts: _monitorConflicts
  property var _monitorConflicts: []

  Process {
    id: findMonitorConflicts
    command: ["sh", "-c", 'cd "$1" 2>/dev/null && grep -lE "^[[:space:]]*hl\\.monitor[[:space:]]*\\(" -- *.lua 2>/dev/null', "sh", root.userDir]
    stdout: StdioCollector {
      onStreamFinished: root._monitorConflicts = root.mode === "managed" ? text.split("\n").filter(name => name !== "").map(name => root.userDir + "/" + name) : []
    }
  }

  // What switching to managed would do, from checkManaged(): "ours" (the
  // file is already axiom's), "adopt" (an existing hyprland.lua is moved to
  // user/), "stock" (it's Hyprland's example config, maybe with install.sh's
  // autostart line, only backed up), "released" (the one leaving managed
  // wrote, unedited: replaced, not kept), "new" (there's none) or
  // "blocked" (a symlinked or git-tracked config is never taken over); ""
  // until checked
  readonly property string managedCheck: _managedCheck.split(":")[0]
  // Why it's blocked: "link" or "git" (in the repository `managedBlockedRepo`)
  readonly property string managedBlockedBy: managedCheck === "blocked" ? _managedCheck.split(":")[1] ?? "" : ""
  readonly property string managedBlockedRepo: managedBlockedBy === "git" ? _managedCheck.split(":").slice(2).join(":") : ""
  property string _managedCheck: ""

  function checkManaged() {
    if (!checkManagedProcess.running)
      checkManagedProcess.running = true;
  }

  Process {
    id: checkManagedProcess
    command: [Paths.scriptsPath + "claim_hyprland.sh", "check", Paths.hyprlandPath, root._header, root.releasedLua()]
    stdout: StdioCollector {
      onStreamFinished: root._managedCheck = text.trim()
    }
  }

  function copyIncludeLines() {
    ClipboardManager.copyText(includeLines);
  }

  function openConfigDir() {
    Quickshell.execDetached(["xdg-open", Paths.hyprlandPath]);
  }

  // --- Driving it ---

  function apply() {
    // Detached, the reload's configreloaded applies the layer again. The
    // file modes go on: their configreloaded doesn't call apply(), so
    // returning would drop a mode switch or a rewrite made with it.
    if (_undoLook() && mode === "detached")
      return;
    if (_appliedMode !== "" && _appliedMode !== mode)
      _leave(_appliedMode);
    _appliedMode = mode;
    if (mode === "included") {
      _writeIfChanged(includePath, moduleLua());
    } else if (mode === "managed") {
      if (!claimManaged.running)
        claimManaged.running = true;
      findMonitorConflicts.running = true;
    } else {
      _problem = "";
      // Not over the managed layer a release is about to take out: its
      // binds would read as the user's
      if (!_releasing)
        _applyRuntime();
    }
  }

  // --- The window look, over the user's config in every mode ---

  // The look's parts last evaluated at runtime ("borders,gaps"), until a
  // config reload drops them. Kept across QML reloads, as Hyprland keeps
  // them.
  PersistentProperties {
    id: _lookState
    reloadableId: "axiomHyprlandLook"
    property string applied: ""
  }

  // After a config reload in the file modes: the module set the look before
  // the user's own lines, so it's evaluated again to win over them. And in
  // every mode as the look or the blur changes (_liveDebounce).
  function _applyLook() {
    const lines = _lookLua(false).concat(_blurLua(false));
    _lookState.applied = HyprLua.lookParts(HyprlandConfig.look).join(",");
    HyprlandManager.runLua(lines.join("\n"));
    HyprlandManager.refreshOptions();
  }

  // A runtime eval can't take a setting back: a part turned off since it
  // was evaluated reloads Hyprland's config, whose configreloaded applies
  // the rest again. True when it reloaded.
  function _undoLook() {
    const now = HyprLua.lookParts(HyprlandConfig.look);
    const dropped = _lookState.applied.split(",").filter(part => part !== "" && !now.includes(part));
    if (dropped.length === 0)
      return false;
    _lookState.applied = "";
    // The file modes rewrite their file, which reloads anyway, unless it
    // never held the part (only evaluated at runtime since its last write)
    if (mode !== "detached" && _appliedMode === mode && status === "loaded" && FileManager.read(mode === "managed" ? managedPath : includePath) !== (mode === "managed" ? managedLua() : moduleLua()))
      return false;
    console.log(`[HyprlandConfigManager] Window look turned off (${dropped.join(", ")}); reloading Hyprland's config to take it back`);
    _reload();
    return true;
  }

  // The mode apply() last set up, "" before the first: only a switch made
  // while axiom runs gives anything back, never a load
  property string _appliedMode: ""
  // While claim_hyprland.sh release runs (detached waits for it)
  property bool _releasing: false

  // Gives back what `previous` took (as the takeover settings do, its own
  // card switching it): leaving managed, the hyprland.lua it claimed
  // (claim_hyprland.sh release); leaving included (or managed, whose
  // restored config may load it), the module, which then does nothing.
  // Otherwise the old layer stays in Hyprland's config, and the runtime
  // layer, which only adds, can't undo it (a strip it set stays a strip).
  function _leave(previous) {
    if (mode !== "included")
      _emptyModule();
    if (previous === "managed") {
      _releasing = true;
      releaseManaged.running = true;
    }
  }

  // The included module once axiom isn't in that mode: every part a no-op,
  // so a hyprland.lua still loading it (setup() or any part) gets nothing
  readonly property string _emptyModuleLua: `${_header}: Hyprland mode isn't "included", so this module does
-- nothing. Switching back to included writes it again.
return setmetatable({}, { __index = function() return function() end end })
`

  function _emptyModule() {
    const current = FileManager.read(includePath);
    if (!current || current === _emptyModuleLua)
      return;
    _writeFile(moduleWriter, includePath, _emptyModuleLua);
  }

  // Everything the layer is made of but the look and the blur; a change
  // re-applies it (in the file modes, rewriting the file, which reloads
  // Hyprland)
  readonly property string _inputs: [mode, HyprlandConfig._bindsJson, HyprlandConfig._monitorsJson, HyprlandConfig._managedJson, WorkspacesConfig._stripsJson, HyprlandConfig.requiredSettings, Theme.baseColorNames.map(name => Theme.resolveColor(name)).join(","), Appearance.animFast, Appearance.animations, Apps.terminalCommand, Apps.fileManagerCommand, Apps.browserCommand, Idle.enabled, PolkitConfig.enabled].join("|")
  on_InputsChanged: _debounce.restart()

  // The window look and the blur behind axiom (paused over a fullscreen
  // window too). A change is only evaluated at runtime, in every mode: a
  // Hyprland reload on every step of a setting stalls the desktop, and
  // detached, re-applying the whole layer redoes every bind. The file
  // holds them as of its last write, and _applyLook evaluates the current
  // ones over it after every reload. Turning a look part off goes through
  // apply(), since an eval can't take a setting back.
  readonly property string _liveInputs: [HyprlandConfig._lookJson, Appearance.blur, BlurManager.active, Appearance.blurBackdrops, Appearance.blurThroughWindows, Theme.borderFocus, Theme.border, Appearance.borderRadius, Appearance.borderWidth].join("|")
  on_LiveInputsChanged: _liveDebounce.restart()

  property Timer _liveDebounce: Timer {
    interval: 300
    onTriggered: {
      const dropped = _lookState.applied.split(",").some(part => part !== "" && !HyprLua.lookParts(HyprlandConfig.look).includes(part));
      if (root._appliedMode !== root.mode || dropped)
        root.apply();
      else
        root._applyLook();
    }
  }

  property Timer _debounce: Timer {
    interval: 300
    onTriggered: root.apply()
  }

  Component.onCompleted: {
    _debounce.restart();
    if (HyprlandConfig.wallpaperDaemon && Appearance.wallpaperBackend === "awww")
      startWallpaperDaemon.running = true;
  }

  Connections {
    target: Hyprland

    function onRawEvent(event) {
      if (event.name !== "configreloaded")
        return;
      root._reloads++;
      // A reload drops runtime binds, rules and the look
      root._monitorsApplied = null;
      _lookState.applied = "";
      if (root.mode === "detached") {
        root._debounce.restart();
      } else {
        root._checkLoaded();
        root._applyLook();
      }
      // Hyprland reloads when a user/*.lua file changes
      if (root.mode === "managed")
        findMonitorConflicts.running = true;
    }
  }

  Process {
    id: unbindRuntime
    command: ["hyprctl", "eval", root._unbindLua]
    onExited: getBinds.running = true
  }

  Process {
    id: getBinds
    command: ["hyprctl", "binds", "-j"]
    stdout: StdioCollector {
      id: bindsCollector
      onStreamFinished: {
        try {
          root._bindList = JSON.parse(bindsCollector.text);
        } catch (e) {
          console.warn("[HyprlandConfigManager] Could not parse hyprctl binds:", e);
          root._bindList = [];
        }
        getAnimations.running = true;
      }
    }
  }

  property var _bindList: []

  Process {
    id: getAnimations
    command: ["hyprctl", "animations", "-j"]
    stdout: StdioCollector {
      id: animationsCollector
      onStreamFinished: {
        let animations = null;
        try {
          animations = JSON.parse(animationsCollector.text);
        } catch (e) {
          console.warn("[HyprlandConfigManager] Could not parse hyprctl animations:", e);
        }
        root._finishRuntime(root._bindList, animations);
      }
    }
  }

  // Output "ok" when the file's marker is set in Hyprland's Lua state
  Process {
    id: checkLoaded
    command: ["hyprctl", "eval", "if not AXIOM_INCLUDED then error('axiom: not loaded') end"]
    stdout: StdioCollector {
      id: loadedCollector
      onStreamFinished: {
        if (root.mode === "detached")
          return;
        if (loadedCollector.text.trim() === "ok") {
          root._problem = "";
          root._loaded = true;
          root._clearRuntime();
          return;
        }
        if (root.mode === "included")
          root._warnOnce(`Hyprland mode is "included", but hyprland.lua doesn't load ${root.includePath}; add:\n${root.includeLines}`);
        else if (root._problem === "")
          root._warnOnce(`Hyprland mode is "managed", but ${root.managedPath} isn't loaded (see hyprctl configerrors)`);
        root._applyRuntime();
      }
    }
  }

  // Makes ~/.config/hypr/hyprland.lua axiom's (scripts/claim_hyprland.sh):
  // "ours" (already), "adopted:<name>" (the old one moved to user/<name>,
  // its lines starting or loading axiom commented out, a dated backup
  // beside it), "created" (there was none), "replaced" (Hyprland's example
  // config, only kept as the backup: its binds and monitor rule would fight
  // axiom's) or "blocked" (a symlinked or git-tracked config is never taken
  // over)
  Process {
    id: claimManaged
    command: [Paths.scriptsPath + "claim_hyprland.sh", "claim", Paths.hyprlandPath, root._header, root.releasedLua()]
    stdout: StdioCollector {
      id: claimCollector
      onStreamFinished: {
        const words = claimCollector.text.trim().split(":");
        const result = words[0];
        if (result === "blocked") {
          root._warnOnce(`Hyprland mode is "managed", but ${Paths.hyprlandPath} is a symlink or in a git repository, so axiom won't take it over; use "included" instead. Applying axiom's layer at runtime meanwhile.`);
          root._applyRuntime();
          return;
        }
        if (result === "adopted")
          console.log(`[HyprlandConfigManager] Took over ${root.managedPath}; your previous one is ${root.userDir}/${words[1]}`);
        else if (result === "replaced")
          console.log(`[HyprlandConfigManager] Replaced ${root.managedPath} (Hyprland's example config is kept as a dated backup beside it; the one axiom gave back isn't kept)`);
        if (["ours", "adopted", "created", "replaced"].includes(result))
          root._writeIfChanged(root.managedPath, root.managedLua());
        // The adopted config's binds would fight axiom's: they move in. Only
        // that file's: the user's other files in user/ are left to the
        // Keybinds page's Merge
        if (result === "adopted" && words[1])
          root.mergeUserBinds(words[1]);
      }
    }
    stderr: StdioCollector {
      id: claimErrors
      onStreamFinished: {
        if (claimErrors.text.trim() !== "")
          console.warn("[HyprlandConfigManager] Taking over hyprland.lua:", claimErrors.text.trim());
      }
    }
  }

  // Gives ~/.config/hypr/hyprland.lua back on leaving managed
  // (scripts/claim_hyprland.sh release): "restored:<from>:<n>" (what the
  // takeover set aside: the adopted user/00-previous*.lua, its lines that
  // start or load axiom enabled again, or the example config's backup;
  // <n> files left in user/ that it doesn't load), "written" (nothing was
  // set aside: releasedLua()), "notours" (already the user's) or
  // "blocked" (a symlinked or git-tracked one, never written)
  Process {
    id: releaseManaged
    command: [Paths.scriptsPath + "claim_hyprland.sh", "release", Paths.hyprlandPath, root._header, root.releasedLua()]
    stdout: StdioCollector {
      id: releaseCollector
      onStreamFinished: {
        const words = releaseCollector.text.trim().split(":");
        const result = words[0];
        root._releasing = false;
        if (result === "restored") {
          console.log(`[HyprlandConfigManager] Gave back ${root.managedPath}: it's ${words[1]} again`);
          if (Number(words[2]) > 0)
            console.warn(`[HyprlandConfigManager] ${root.managedPath} is your previous config again, which doesn't load ${root.userDir}/*.lua (${words[2]} files): load them from it if you still want them`);
        } else if (result === "written") {
          console.log(`[HyprlandConfigManager] Gave back ${root.managedPath}: it now starts axiom and loads ${root.userDir}/*.lua, and is yours to edit`);
        } else if (result === "blocked") {
          console.warn(`[HyprlandConfigManager] ${root.managedPath} is a symlink or in a git repository, so axiom didn't give it back: it still loads axiom's managed layer`);
        }
        // A reload brings the given-back config in, and with it the runtime
        // layer (configreloaded); without one, the runtime layer goes on now
        if (result === "restored" || result === "written")
          root._reload();
        else if (root.mode === "detached")
          root._applyRuntime();
      }
    }
    stderr: StdioCollector {
      id: releaseErrors
      onStreamFinished: {
        if (releaseErrors.text.trim() !== "")
          console.warn("[HyprlandConfigManager] Giving back hyprland.lua:", releaseErrors.text.trim());
      }
    }
  }

  // --- Moving the user's binds into axiom (managed mode) ---

  // scripts/merge_hypr_binds.py: every hl.bind in user/*.lua that can move
  // becomes one of axiom's binds (an action where one does the same, else
  // the `lua` action), saved first, then its call is deleted from the file
  // (a dated backup beside it). A call that couldn't be deleted has its
  // binds taken back out of axiom's, so no key is ever bound twice. A key
  // axiom binds too stays one bind, the user's replacing axiom's
  // (HyprBinds.mergeBinds). Runs by itself on the adopted file when a
  // takeover adopts the previous hyprland.lua, so managed mode starts with
  // no conflicts; the Keybinds page's Merge runs it on all of user/.
  readonly property bool merging: extractBinds.running || removeBinds.running
  // The last merge: { moved, removed, kept: [{ file, line, key, reason,
  // detail }], failed: [{ file, line, reason, detail }], remapped: [{ from,
  // to, action }], tracked: [file], errors: [text], saveFailed }, or null.
  // Reasons are codes (merge_hypr_binds.py, and "crashed"), which the
  // Keybinds page translates
  property var lastMerge: null
  // How many binds a Merge of all of user/ would move (previewMerge());
  // -1 until looked
  property int mergeable: -1
  // The binds a merge moved in for good (KeybindManager adds them to a
  // draft with unsaved edits)
  signal bindsMerged(var binds)

  // `only`: one file name in user/ (the adopted one), else all of them
  function mergeUserBinds(only) {
    if (mode !== "managed" || merging)
      return;
    _preview = false;
    _run(only);
  }

  // Counts what a Merge would move, changing nothing (`mergeable`)
  function previewMerge() {
    if (mode !== "managed" || merging)
      return;
    _preview = true;
    _run("");
  }

  property bool _preview: false
  property var _merged: null
  // The saved binds before a merge, and its sites, to take back what
  // couldn't be deleted
  property var _before: []
  property var _sites: []

  function _run(only) {
    extractBinds.command = [Paths.scriptsPath + "merge_hypr_binds.py", "extract", Paths.hyprlandPath].concat(only ? ["--only", only] : []);
    extractBinds.running = true;
  }

  function _extracted(text) {
    let found;
    try {
      found = JSON.parse(text);
    } catch (e) {
      if (_preview) {
        mergeable = 0;
        return;
      }
      console.warn("[HyprlandConfigManager] Reading your Hyprland binds failed:", extractErrors.text.trim() || e);
      lastMerge = {
        "moved": 0,
        "removed": 0,
        "kept": [],
        "failed": [],
        "remapped": [],
        "tracked": [],
        "errors": [extractErrors.text.trim() || String(e)]
      };
      return;
    }
    if (_preview) {
      mergeable = found.binds.length;
      return;
    }
    _merged = {
      "moved": found.binds.length,
      "removed": 0,
      "kept": found.kept,
      "failed": [],
      "remapped": found.remapped,
      "tracked": found.tracked,
      "errors": found.errors
    };
    if (found.binds.length === 0) {
      lastMerge = _merged;
      mergeable = 0;
      return;
    }
    // Saved before the calls go, so no bind is ever missing
    _before = HyprlandConfig.binds;
    _sites = found.sites;
    if (!SettingsManager.commitValues({
      "Hyprland.binds": HyprBinds.mergeBinds(_before, found.binds)
    })) {
      _merged.moved = 0;
      _merged.saveFailed = true;
      lastMerge = _merged;
      return;
    }
    removeBinds.command = [Paths.scriptsPath + "merge_hypr_binds.py", "remove", Paths.hyprlandPath, JSON.stringify(found.sites)];
    removeBinds.running = true;
  }

  // After the removal: the binds whose call is still in its file go back
  // out of axiom's (the saved binds from before, with only the rest merged)
  function _removed(done) {
    const left = site => done.failed.some(f => f.file === site.file && (f.line === 0 || f.line === site.line));
    const moved = [].concat(..._sites.filter(site => !left(site)).map(site => site.binds));
    if (done.failed.length > 0 && !SettingsManager.commitValues({
      "Hyprland.binds": HyprBinds.mergeBinds(_before, moved)
    }))
      console.warn("[HyprlandConfigManager] Couldn't take the binds left in your Hyprland config back out of axiom's");
    _merged.moved = moved.length;
    _merged.removed = done.removed;
    _merged.failed = done.failed;
    for (const failure of done.failed)
      console.warn("[HyprlandConfigManager] Left the binds in", failure.file, failure.line > 0 ? `(line ${failure.line})` : "", "where they were:", failure.reason, failure.detail);
    if (moved.length > 0)
      bindsMerged(moved);
    lastMerge = _merged;
    mergeable = -1;
    console.log(`[HyprlandConfigManager] Moved ${moved.length} binds from ${root.userDir} into axiom; ${_merged.kept.length} stay there`);
  }

  Process {
    id: extractBinds
    stdout: StdioCollector {
      onStreamFinished: root._extracted(text)
    }
    stderr: StdioCollector {
      id: extractErrors
    }
  }

  Process {
    id: removeBinds
    stdout: StdioCollector {
      onStreamFinished: {
        let done;
        try {
          done = JSON.parse(text);
        } catch (e) {
          // Nothing is known to be deleted: every file's binds go back
          done = {
            "removed": 0,
            "files": []
          };
          done.failed = root._sites.map(site => ({
                "file": site.file,
                "line": 0,
                "reason": "crashed",
                "detail": removeErrors.text.trim() || String(e)
              })).filter((f, i, all) => all.findIndex(other => other.file === f.file) === i);
        }
        root._removed(done);
      }
    }
    stderr: StdioCollector {
      id: removeErrors
    }
  }

  // Writes `text` to `path` through `view`, reading the file first: a
  // FileView skips setText of the text it last read or wrote, which the
  // file may no longer hold (release replaced it, or the user edited it)
  function _writeFile(view, path, text) {
    view.path = "";
    view.path = path;
    view.setText(text);
  }

  FileView {
    id: writer
    atomicWrites: true
    blockLoading: true
    printErrors: false
    onSaved: root._reload()
    onSaveFailed: error => console.warn("[HyprlandConfigManager] Could not write", writer.path, error)
  }

  // The included module emptied (_emptyModule), apart from `writer`, which
  // a takeover may be using at the same time
  FileView {
    id: moduleWriter
    atomicWrites: true
    blockLoading: true
    printErrors: false
    onSaved: root._reload()
    onSaveFailed: error => console.warn("[HyprlandConfigManager] Could not write", moduleWriter.path, error)
  }

  // Reloads Hyprland, again once the running reload ends if one is asked
  // for meanwhile (a file written then would otherwise be missed)
  function _reload() {
    if (reload.running)
      _reloadAgain = true;
    else
      reload.running = true;
  }

  property bool _reloadAgain: false

  Process {
    id: reload
    command: ["hyprctl", "reload"]
    onExited: {
      if (root._reloadAgain) {
        root._reloadAgain = false;
        reload.running = true;
      }
    }
  }

  // Installed cursor themes (XCursor or hyprcursor), for the settings page
  readonly property var cursorThemes: _cursorThemes
  property var _cursorThemes: []

  Process {
    id: listCursorThemes
    running: true
    command: ["sh", "-c", `for d in "$HOME/.icons" "\${XDG_DATA_HOME:-$HOME/.local/share}/icons" /usr/share/icons; do for t in "$d"/*; do [ -d "$t/cursors" ] || [ -f "$t/manifest.hl" ] && basename "$t"; done; done | sort -u`]
    stdout: StdioCollector {
      onStreamFinished: root._cursorThemes = text.split("\n").filter(name => name !== "")
    }
  }

  Process {
    id: startWallpaperDaemon
    command: ["sh", "-c", "command -v awww-daemon >/dev/null || exit 0; awww query >/dev/null 2>&1 || setsid -f awww-daemon >/dev/null 2>&1"]
  }
}
