pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland

import qs.config
import qs.components.methods

/*
 * Sets Hyprland up for axiom (the Hyprland section, HyprlandConfig.mode).
 * One Lua "layer" (binds, required settings, themed borders, blur) reaches
 * Hyprland in one of three ways:
 *   detached  evaluated at runtime (hyprctl eval), again after every config
 *             reload, which drops it; binds on keys already taken are skipped
 *   included  written to $XDG_STATE_HOME/axiom/hyprland.lua, a module the
 *             user's hyprland.lua loads (includeLines)
 *   managed   written into ~/.config/hypr/hyprland.lua itself, with the
 *             Managed config, loading ~/.config/hypr/user/*.lua after it
 * Whenever the file isn't loaded (included but the lines are missing, or a
 * managed takeover refused), the runtime layer is applied instead, so axiom
 * still works, and `problem` says why.
 */
Singleton {
  id: root

  readonly property string mode: HyprlandConfig.mode
  // Why the chosen mode isn't in effect, or ""
  readonly property string problem: _problem
  property string _problem: ""
  // "runtime" (detached), "loaded" (the file is in effect), "fallback"
  // (it isn't: see `problem`) or "pending" (still checking)
  readonly property string status: mode === "detached" ? "runtime" : _problem !== "" ? "fallback" : _loaded ? "loaded" : "pending"
  property bool _loaded: false
  // Configured keys the runtime layer skipped because Hyprland's config
  // already binds them
  readonly property var skippedKeys: _skippedKeys
  property var _skippedKeys: []
  // A problem belongs to the mode it was found in
  onModeChanged: {
    _problem = "";
    _loaded = false;
  }

  readonly property string includePath: Paths.userStatePath + "hyprland.lua"
  readonly property string managedPath: Paths.hyprlandPath + "hyprland.lua"
  readonly property string userDir: Paths.hyprlandPath + "user"
  // What the user's hyprland.lua needs for the included mode
  readonly property string includeLines: `local ok, axiom = pcall(dofile, ${_lua(includePath)})\nif ok then axiom.setup() end`

  readonly property string _shellCommand: `qs -p '${Paths.axiomPath.replace(/\/$/, "")}'`
  readonly property string _header: "-- Generated by axiom"

  // --- The Lua layer ---

  // Actions (the schema's Hyprland.binds[].action) as IPC calls, with the
  // default label and the section on the Keybinds page. I18n.tr isn't used:
  // labels go to Hyprland, like the user's own bind descriptions.
  readonly property var _actions: ({
      "launcher": ["appLauncher toggle", "App launcher", "Axiom"],
      "launcherSearch": ["appLauncher search {0}", "Launcher: {0}", "Axiom"],
      "overlay": ["overlay toggle", "Overlay", "Axiom"],
      "overlayPage": ["overlay page {0}", "Overlay: {0}", "Axiom"],
      "edgeMenu": ["edgeMenu toggle {0}", "Edge menu: {0}", "Axiom"],
      "workspaceOverview": ["workspaceOverlay toggle", "Workspace overview", "Workspace"],
      "powerMenu": ["powermenu toggle", "Power menu", "Axiom"],
      "lock": ["lockscreen lock", "Lock", "Axiom"],
      "toggleDnd": ["notifications toggleDnd", "Do not disturb", "Axiom"],
      "clearNotifications": ["notifications clear", "Clear notifications", "Axiom"],
      "idleInhibit": ["idleInhibit toggle", "Caffeine", "Axiom"],
      "workspaceStep": ["workspaces step {0} go", "Switch {0}", "Workspace"],
      "moveWindowStep": ["workspaces step {0} move", "Move window {0}", "Workspace"],
      "workspaceNth": ["workspaces nth {0} go", "Go to workspace {0}", "Workspace"],
      "moveWindowStepSilent": ["workspaces step {0} moveSilent", "Send window {0}", "Workspace"],
      "moveWindowNth": ["workspaces nth {0} move", "Move window to workspace {0}", "Workspace"],
      "moveWindowNthSilent": ["workspaces nth {0} moveSilent", "Send window to workspace {0}", "Workspace"],
      "volumeUp": ["audio volumeUp", "Volume up", "Media"],
      "volumeDown": ["audio volumeDown", "Volume down", "Media"],
      "toggleMute": ["audio toggleMute", "Mute", "Media"],
      "toggleMicMute": ["audio toggleMicMute", "Mute microphone", "Media"],
      "mediaPlayPause": ["media playPause", "Play/Pause", "Media"],
      "mediaNext": ["media next", "Next track", "Media"],
      "mediaPrevious": ["media previous", "Previous track", "Media"]
    })

  // Actions that are Hyprland dispatchers, bound directly: the dispatcher's
  // Lua (from the argument), the default label and the section
  readonly property var _dispatchers: ({
      "focusDir": [arg => `hl.dsp.focus({ direction = ${_lua(arg)} })`, "Focus {0}", "Window"],
      "moveWindowDir": [arg => `hl.dsp.window.move({ direction = ${_lua(arg)} })`, "Move {0}", "Window"],
      "resizeWindow": [arg => {
          const [x, y] = arg.split(/[\s,]+/).map(Number);
          return isFinite(x) && isFinite(y) ? `hl.dsp.window.resize({ x = ${x}, y = ${y}, relative = true })` : "";
        }, "Resize by {0}", "Window"],
      "closeWindow": [() => "hl.dsp.window.close()", "Close", "Window"],
      "fullscreen": [() => "hl.dsp.window.fullscreen()", "Fullscreen", "Window"],
      "toggleFloat": [() => `hl.dsp.window.float({ action = "toggle" })`, "Toggle floating", "Window"],
      "pin": [() => "hl.dsp.window.pin()", "Pin", "Window"],
      "centerWindow": [() => "hl.dsp.window.center()", "Center", "Window"],
      "toggleGroup": [() => "hl.dsp.group.toggle()", "Toggle group", "Window"],
      // On a mouse button (SUPER + mouse:272), which Hyprland makes a
      // mouse bind by itself
      "mouseDrag": [() => "hl.dsp.window.drag()", "Drag", "Window"],
      "mouseResize": [() => "hl.dsp.window.resize()", "Resize", "Window"],
      "toggleSpecial": [arg => `hl.dsp.workspace.toggle_special(${_lua(arg)})`, "Toggle {0}", "Special"],
      "moveToSpecial": [arg => `hl.dsp.window.move({ workspace = ${_lua("special:" + arg)} })`, "Move window to {0}", "Special"]
    })

  // Flags an action starts with when it's picked (the bind can change them)
  readonly property var actionFlags: ({
      "resizeWindow": ["repeating"],
      "volumeUp": ["locked", "repeating"],
      "volumeDown": ["locked", "repeating"],
      "toggleMute": ["locked"],
      "toggleMicMute": ["locked"],
      "mediaPlayPause": ["locked"],
      "mediaNext": ["locked"],
      "mediaPrevious": ["locked"]
    })
  readonly property var flagNames: ["repeating", "locked", "release"]

  // The section a bind's action files it under on the Keybinds page
  function sectionFor(action) {
    return _actions[action]?.[2] ?? _dispatchers[action]?.[2] ?? "Axiom";
  }

  // The label a bind gets when its description is empty
  function defaultLabel(bind) {
    const argument = String(bind.argument ?? "").trim();
    if (bind.action === "exec")
      return argument;
    return (_actions[bind.action]?.[1] ?? _dispatchers[bind.action]?.[1] ?? "").replace("{0}", argument);
  }

  // Whether a description names its own section ("Section: Label")
  function hasOwnSection(description) {
    return /^[^:]+: \S/.test(String(description ?? "").trim());
  }

  // The description Hyprland gets: "Section: Label", the section from the
  // action unless the description names its own
  function descriptionFor(bind) {
    const own = String(bind.description ?? "").trim();
    return hasOwnSection(own) ? own : sectionFor(bind.action) + ": " + (own || defaultLabel(bind));
  }

  // A Lua string literal
  function _lua(text) {
    return HyprLua.string(text);
  }

  // A single-quoted shell word
  function _shellWord(text) {
    return "'" + String(text).replace(/'/g, "'\\''") + "'";
  }

  function _hex(color) {
    return [color.r, color.g, color.b].map(v => Math.round(v * 255).toString(16).padStart(2, "0")).join("");
  }

  // The hl.bind() line for a configured bind, or "" when it's incomplete
  function _bindLua(bind) {
    const argument = String(bind.argument ?? "").trim();
    if (!String(bind.key ?? "").trim() || (_needsArgument(bind.action) && !argument))
      return "";
    let dispatcher;
    if (_dispatchers[bind.action]) {
      dispatcher = _dispatchers[bind.action][0](argument);
    } else if (bind.action === "exec") {
      dispatcher = `hl.dsp.exec_cmd(${_lua(argument)})`;
    } else if (_actions[bind.action]) {
      dispatcher = `hl.dsp.exec_cmd(${_lua(`${_shellCommand} ipc call ${_actions[bind.action][0].replace("{0}", _shellWord(argument))}`)})`;
    }
    if (!dispatcher)
      return "";
    const options = [`description = ${_lua(descriptionFor(bind))}`];
    for (const flag of flagNames)
      if (bind[flag])
        options.push(`${flag} = true`);
    return `hl.bind(${_lua(bind.key.trim())}, ${dispatcher}, { ${options.join(", ")} })`;
  }

  // Whether a configured bind has everything it needs to be bound
  function isComplete(bind) {
    return _bindLua(bind) !== "";
  }

  function _needsArgument(action) {
    return action === "exec" || (_actions[action]?.[0] ?? _dispatchers[action]?.[1] ?? "").includes("{0}");
  }

  function _requiredLua(withAnimation) {
    const lines = ["hl.config({ misc = { allow_session_lock_restore = true } })"];
    if (withAnimation)
      lines.push(`hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "default", style = "slide" })`);
    return lines;
  }

  function _themeLua() {
    return [`hl.config({ general = { col = { active_border = "rgb(${_hex(Theme.borderFocus)})", inactive_border = "rgb(${_hex(Theme.border)})" } } })`];
  }

  function _blurLua() {
    return [`hl.layer_rule({ match = { namespace = "^axiom-(bar|edge-popout|launcher)$" }, blur = true, ignore_alpha = 0.2 })`];
  }

  function _indent(lines, prefix) {
    return lines.map(line => line === "" ? "" : prefix + line).join("\n");
  }

  // The included file: a module whose setup() applies what's enabled
  function moduleLua() {
    const binds = HyprlandConfig.binds.map(bind => _bindLua(bind)).filter(line => line !== "");
    const setup = [];
    if (HyprlandConfig.requiredSettings)
      setup.push("M.required()");
    setup.push("M.binds()");
    if (HyprlandConfig.theme)
      setup.push("M.theme()");
    if (HyprlandConfig.blur)
      setup.push("M.blur()");
    return `${_header} from its Hyprland settings, and rewritten whenever they
-- (or the theme) change: edit those, not this file.
--
-- Load it near the top of hyprland.lua, so what follows overrides it:
--   ${includeLines.replace("\n", "\n--   ")}
-- setup() applies everything enabled in axiom's settings; call the parts
-- instead to pick. hl.unbind("KEY") after it frees one of axiom's keys.
local M = {}

-- Session lock restore and a workspaces animation (axiom's grid slides)
function M.required()
${_indent(_requiredLua(true), "  ")}
end

function M.binds()
${_indent(binds, "  ")}
end

-- Window borders from the axiom theme
function M.theme()
${_indent(_themeLua(), "  ")}
end

-- Blur behind the bars, edge popouts and launcher
function M.blur()
${_indent(_blurLua(), "  ")}
end

function M.setup()
${_indent(setup, "  ")}
end

-- Lets axiom see that this file is loaded
AXIOM_INCLUDED = true

return M
`;
  }

  function _cursorLua(m) {
    if (!m.cursorTheme)
      return "";
    return `hl.env("XCURSOR_THEME", ${_lua(m.cursorTheme)})\nhl.env("XCURSOR_SIZE", ${_lua(String(m.cursorSize))})\n`;
  }

  // What the managed file runs once Hyprland has started: the cursor,
  // axiom, then the autostart commands
  function _startLua(m) {
    const lines = [];
    if (m.cursorTheme)
      lines.push(`hl.exec_cmd(${_lua(`hyprctl setcursor ${_shellWord(m.cursorTheme)} ${m.cursorSize}`)})`);
    lines.push(`hl.exec_cmd(${_lua(_shellCommand)})`);
    for (const entry of m.autostart)
      if (entry.enabled && entry.command.trim() !== "")
        lines.push(`hl.exec_cmd(${_lua(entry.command.trim())})`);
    return lines;
  }

  function _envLua(m) {
    return m.env.filter(entry => /^[A-Za-z_][A-Za-z0-9_]*$/.test(entry.name.trim())).map(entry => `hl.env(${_lua(entry.name.trim())}, ${_lua(entry.value)})\n`).join("");
  }

  // Animation presets: curves { name: [x1, y1, x2, y2] } and leaves
  // [leaf, speed (Hyprland's unit: 100 ms), curve, style]
  readonly property var _animationPresets: ({
      "snappy": {
        "curves": {
          "axiomSnappy": [0.2, 0, 0, 1]
        },
        "leaves": [["windows", 2, "axiomSnappy", "popin 90%"], ["layers", 2, "axiomSnappy", "fade"], ["fade", 2, "axiomSnappy", ""], ["border", 1, "axiomSnappy", ""], ["workspaces", 2.5, "axiomSnappy", "slide"], ["specialWorkspace", 2.5, "axiomSnappy", "slidevert"]]
      },
      "bouncy": {
        "curves": {
          "axiomSnappy": [0.2, 0, 0, 1],
          "axiomOvershoot": [0.34, 1.56, 0.64, 1]
        },
        "leaves": [["windows", 4, "axiomOvershoot", "popin 60%"], ["windowsOut", 3, "axiomSnappy", "popin 80%"], ["layers", 3, "axiomOvershoot", "fade"], ["fade", 3, "axiomSnappy", ""], ["border", 2, "axiomSnappy", ""], ["workspaces", 4, "axiomOvershoot", "slide"], ["specialWorkspace", 4, "axiomOvershoot", "slidevert"]]
      }
    })

  // The preset (or custom list) as { curves, leaves }, or null for
  // Hyprland's own animations
  function _animationSet(m) {
    switch (m.animationPreset) {
    case "axiom":
      {
        // Look & Feel → Motion: the shell's durations, in Hyprland's unit
        const speed = ms => Math.max(0.1, ms / 100);
        return {
          "curves": {
            "axiomMotion": [0.05, 0.7, 0.1, 1]
          },
          "leaves": [["windows", speed(Appearance.animSlow), "axiomMotion", "popin 80%"], ["layers", speed(Appearance.animNormal), "axiomMotion", "fade"], ["fade", speed(Appearance.animNormal), "axiomMotion", ""], ["border", speed(Appearance.animFast), "axiomMotion", ""], ["workspaces", speed(Appearance.animSlow), "axiomMotion", "slide"], ["specialWorkspace", speed(Appearance.animSlow), "axiomMotion", "slidevert"]]
        };
      }
    case "custom":
      {
        const curves = {};
        for (const curve of m.curves) {
          const points = curve.points.split(",").map(Number);
          if (curve.name.trim() !== "" && points.length === 4 && points.every(isFinite))
            curves[curve.name.trim()] = points;
        }
        return {
          "curves": curves,
          "leaves": m.customAnimations.map(a => [a.leaf, a.enabled ? a.durationMs / 100 : 0, a.curve.trim() || "default", a.style.trim()])
        };
      }
    }
    return _animationPresets[m.animationPreset] ?? null;
  }

  function _animationsLua(m) {
    // Following axiom's motion while it's off: animations are off (_configLua)
    const off = !m.animations || (m.animationPreset === "axiom" && !Appearance.animations);
    const set = off ? null : _animationSet(m);
    if (!set)
      return "";
    const lines = Object.keys(set.curves).map(name => {
      const p = set.curves[name].map(v => HyprLua.value(v));
      return `hl.curve(${_lua(name)}, { type = "bezier", points = { { ${p[0]}, ${p[1]} }, { ${p[2]}, ${p[3]} } } })`;
    });
    for (const [leaf, speed, curve, style] of set.leaves) {
      const parts = [`leaf = ${_lua(leaf)}`, `enabled = ${speed > 0}`];
      if (speed > 0)
        parts.push(`speed = ${HyprLua.value(speed)}`, `bezier = ${_lua(curve)}`);
      if (speed > 0 && style !== "")
        parts.push(`style = ${_lua(style)}`);
      lines.push(`hl.animation({ ${parts.join(", ")} })`);
    }
    return "\n" + lines.join("\n") + "\n";
  }

  // The managed settings as one hl.config() table
  function _configLua(m) {
    const look = _look(m);
    const overrides = {
      "decoration.rounding": look.rounding,
      "general.border_size": look.borderSize
    };
    // Following axiom's motion includes turning animations off with it
    if (m.animationPreset === "axiom" && !Appearance.animations)
      overrides["animations.enabled"] = false;
    const schema = ConfigManager.configSchema?.properties?.Hyprland?.properties?.managed;
    return `hl.config(${HyprLua.serialize(HyprLua.configTable(schema, m, name => _hex(Theme.resolveColor(name)), overrides))})`;
  }

  // Window rounding and border width: axiom's shape, or the managed values
  function _look(m) {
    return m.matchAxiom ? {
      "rounding": Appearance.borderRadius,
      "borderSize": Appearance.borderWidth
    } : {
      "rounding": m.rounding,
      "borderSize": m.borderSize
    };
  }

  // The managed hyprland.lua
  function managedLua() {
    const m = HyprlandConfig.managed;
    const module = moduleLua().split("\n").filter(line => !line.startsWith("--")).join("\n").trim();
    return `${_header} (Hyprland mode: managed) from its Hyprland settings,
-- and rewritten whenever they (or the theme) change: edit those, not this file.
-- Your own config goes in ${userDir}/*.lua, loaded after this in name
-- order, so it overrides it. hl.unbind("KEY") there frees one of axiom's keys.

local axiom = (function()
${_indent(module.split("\n"), "  ")}
end)()

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
${_envLua(m)}
${_configLua(m)}
${_cursorLua(m)}
axiom.setup()
${_animationsLua(m)}
hl.on("hyprland.start", function()
${_indent(_startLua(m), "  ")}
end)

-- Your files, through require (as user.<name>) so Hyprland reloads when
-- one changes. Shared modules go in user/lib/ (require("user.lib.x")),
-- which isn't loaded here. A failing file doesn't stop the rest; the
-- errors are raised together at the end (hyprctl configerrors).
local errors = {}
local files = io.popen("cd " .. ${_lua(_shellWord(userDir))} .. " 2>/dev/null && ls -1 *.lua 2>/dev/null")
if files then
  for file in files:lines() do
    local ok, err = pcall(require, "user." .. file:gsub("%.lua$", ""))
    if not ok then errors[#errors + 1] = tostring(err) end
  end
  files:close()
end
if #errors > 0 then error(table.concat(errors, "\\n")) end
`;
  }

  // --- Runtime (detached, and the fallback) ---

  // Keys this layer bound at runtime live in Hyprland's Lua state
  // (AXIOM_RUNTIME_KEYS), which a config reload resets along with the
  // binds, and which outlives a reload of the shell. They're unbound
  // before the binds are read, so they don't look like the user's.
  readonly property string _unbindLua: "for _, key in ipairs(AXIOM_RUNTIME_KEYS or {}) do hl.unbind(key) end\nAXIOM_RUNTIME_KEYS = nil"
  // Keys skipped as taken, so each is only reported once
  property var _reportedTaken: ({})
  property bool _runtimeWanted: false

  function _applyRuntime() {
    _runtimeWanted = true;
    if (!unbindRuntime.running && !getBinds.running)
      unbindRuntime.running = true;
  }

  function _clearRuntime() {
    _runtimeWanted = false;
    _skippedKeys = [];
    HyprlandManager.runLua(_unbindLua);
    KeybindManager.refreshSoon();
  }

  function _finishRuntime(bindList, animations) {
    if (!_runtimeWanted)
      return;
    const plan = HyprBinds.runtimeBinds(HyprlandConfig.binds.filter(bind => _bindLua(bind) !== ""), bindList);
    for (const key of plan.unreadable)
      console.warn(`[HyprlandConfigManager] Can't read the key "${key}"; bind it as MODS + KEY`);
    for (const key of plan.skipped) {
      const id = HyprBinds.keyId(key);
      if (!_reportedTaken[id])
        console.log(`[HyprlandConfigManager] ${key} is bound by your Hyprland config; skipping axiom's bind`);
      _reportedTaken[id] = true;
    }
    const lines = plan.apply.map(bind => _bindLua(bind));
    const keys = plan.apply.map(bind => bind.key.trim());
    const skipped = plan.skipped;
    if (HyprlandConfig.requiredSettings) {
      const anim = (Array.isArray(animations?.[0]) ? animations[0] : []).find(a => a.name === "workspaces");
      lines.push(..._requiredLua(!anim?.overridden));
    }
    if (HyprlandConfig.theme)
      lines.push(..._themeLua());
    if (HyprlandConfig.blur)
      lines.push(..._blurLua());
    lines.push(`AXIOM_RUNTIME_KEYS = { ${keys.map(key => _lua(key)).join(", ")} }`);
    _skippedKeys = skipped;
    HyprlandManager.runLua(lines.join("\n"));
    HyprlandManager.refreshOptions();
    KeybindManager.refreshSoon();
  }

  // --- Files (included, managed) ---

  // Writes `text` to `path` unless it's already there; then reloads
  // Hyprland, since it doesn't watch files a config loads
  function _writeIfChanged(path, text) {
    if (FileManager.read(path) === text) {
      _checkLoaded();
      return;
    }
    root._pendingWrite = {
      "path": path,
      "text": text
    };
    makeDir.command = ["mkdir", "-p", path.replace(/\/[^/]*$/, "")];
    makeDir.running = true;
  }

  property var _pendingWrite: null

  Process {
    id: makeDir
    onExited: code => {
      const write = root._pendingWrite;
      root._pendingWrite = null;
      if (code !== 0 || !write) {
        console.warn("[HyprlandConfigManager] Could not create the folder for", write?.path);
        return;
      }
      writer.path = write.path;
      writer.setText(write.text);
    }
  }

  // After a (re)load: is the file in effect? If not, the runtime layer
  // stands in for it
  function _checkLoaded() {
    if (!checkLoaded.running)
      checkLoaded.running = true;
  }

  function _warnOnce(message) {
    if (_problem === message)
      return;
    _problem = message;
    console.warn("[HyprlandConfigManager]", message);
  }

  // --- For the settings page ---

  // What switching to managed would do, from checkManaged(): "ours" (the
  // file is already axiom's), "adopt" (an existing hyprland.lua is moved to
  // user/), "new" (there's none) or "blocked" (a symlinked or git-tracked
  // config is never taken over); "" until checked
  readonly property string managedCheck: _managedCheck
  property string _managedCheck: ""

  function checkManaged() {
    if (!checkManagedProcess.running)
      checkManagedProcess.running = true;
  }

  Process {
    id: checkManagedProcess
    command: [Paths.scriptsPath + "claim_hyprland.sh", "check", Paths.hyprlandPath, root._header]
    stdout: StdioCollector {
      onStreamFinished: root._managedCheck = text.trim()
    }
  }

  function copyIncludeLines() {
    Quickshell.execDetached(["wl-copy", "--", includeLines]);
  }

  function openConfigDir() {
    Quickshell.execDetached(["xdg-open", Paths.hyprlandPath]);
  }

  // --- Driving it ---

  function apply() {
    if (mode === "included") {
      _writeIfChanged(includePath, moduleLua());
    } else if (mode === "managed") {
      if (!claimManaged.running)
        claimManaged.running = true;
    } else {
      _problem = "";
      _applyRuntime();
    }
  }

  // Everything the layer is made of; a change re-applies it
  readonly property string _inputs: [mode, HyprlandConfig._bindsJson, HyprlandConfig._managedJson, HyprlandConfig.requiredSettings, HyprlandConfig.theme, HyprlandConfig.blur, Theme.borderFocus, Theme.border, Theme.baseColorNames.map(name => Theme.resolveColor(name)).join(","), Appearance.borderRadius, Appearance.borderWidth, Appearance.animFast, Appearance.animations].join("|")
  on_InputsChanged: _debounce.restart()

  property Timer _debounce: Timer {
    interval: 300
    onTriggered: root.apply()
  }

  Component.onCompleted: {
    _debounce.restart();
    if (HyprlandConfig.wallpaperDaemon)
      startWallpaperDaemon.running = true;
  }

  Connections {
    target: Hyprland

    function onRawEvent(event) {
      if (event.name !== "configreloaded")
        return;
      // A reload drops runtime binds and rules
      if (root.mode === "detached")
        root._debounce.restart();
      else
        root._checkLoaded();
    }
  }

  Process {
    id: unbindRuntime
    command: ["hyprctl", "eval", root._unbindLua]
    onExited: getBinds.running = true
  }

  Process {
    id: getBinds
    command: ["hyprctl", "binds", "-j"]
    stdout: StdioCollector {
      id: bindsCollector
      onStreamFinished: {
        try {
          root._bindList = JSON.parse(bindsCollector.text);
        } catch (e) {
          console.warn("[HyprlandConfigManager] Could not parse hyprctl binds:", e);
          root._bindList = [];
        }
        getAnimations.running = true;
      }
    }
  }

  property var _bindList: []

  Process {
    id: getAnimations
    command: ["hyprctl", "animations", "-j"]
    stdout: StdioCollector {
      id: animationsCollector
      onStreamFinished: {
        let animations = null;
        try {
          animations = JSON.parse(animationsCollector.text);
        } catch (e) {
          console.warn("[HyprlandConfigManager] Could not parse hyprctl animations:", e);
        }
        root._finishRuntime(root._bindList, animations);
      }
    }
  }

  // Output "ok" when the file's marker is set in Hyprland's Lua state
  Process {
    id: checkLoaded
    command: ["hyprctl", "eval", "if not AXIOM_INCLUDED then error('axiom: not loaded') end"]
    stdout: StdioCollector {
      id: loadedCollector
      onStreamFinished: {
        if (root.mode === "detached")
          return;
        if (loadedCollector.text.trim() === "ok") {
          root._problem = "";
          root._loaded = true;
          root._clearRuntime();
          return;
        }
        if (root.mode === "included")
          root._warnOnce(`Hyprland mode is "included", but hyprland.lua doesn't load ${root.includePath}; add:\n${root.includeLines}`);
        else if (root._problem === "")
          root._warnOnce(`Hyprland mode is "managed", but ${root.managedPath} isn't loaded (see hyprctl configerrors)`);
        root._applyRuntime();
      }
    }
  }

  // Makes ~/.config/hypr/hyprland.lua axiom's (scripts/claim_hyprland.sh):
  // "ours" (already), "adopted" (the old one moved to user/00-previous.lua,
  // a dated backup beside it) or "blocked" (a symlinked or git-tracked
  // config is never taken over)
  Process {
    id: claimManaged
    command: [Paths.scriptsPath + "claim_hyprland.sh", "claim", Paths.hyprlandPath, root._header]
    stdout: StdioCollector {
      id: claimCollector
      onStreamFinished: {
        const result = claimCollector.text.trim();
        if (result === "blocked") {
          root._warnOnce(`Hyprland mode is "managed", but ${Paths.hyprlandPath} is a symlink or in a git repository, so axiom won't take it over; use "included" instead. Applying axiom's layer at runtime meanwhile.`);
          root._applyRuntime();
          return;
        }
        if (result === "adopted")
          console.log(`[HyprlandConfigManager] Took over ${root.managedPath}; your previous one is ${root.userDir}/00-previous.lua`);
        if (result === "ours" || result === "adopted")
          root._writeIfChanged(root.managedPath, root.managedLua());
      }
    }
    stderr: StdioCollector {
      id: claimErrors
      onStreamFinished: {
        if (claimErrors.text.trim() !== "")
          console.warn("[HyprlandConfigManager] Taking over hyprland.lua:", claimErrors.text.trim());
      }
    }
  }

  FileView {
    id: writer
    atomicWrites: true
    printErrors: false
    onSaved: reload.running = true
    onSaveFailed: error => console.warn("[HyprlandConfigManager] Could not write", writer.path, error)
  }

  Process {
    id: reload
    command: ["hyprctl", "reload"]
  }

  // Installed cursor themes (XCursor or hyprcursor), for the settings page
  readonly property var cursorThemes: _cursorThemes
  property var _cursorThemes: []

  Process {
    id: listCursorThemes
    running: true
    command: ["sh", "-c", `for d in "$HOME/.icons" "\${XDG_DATA_HOME:-$HOME/.local/share}/icons" /usr/share/icons; do for t in "$d"/*; do [ -d "$t/cursors" ] || [ -f "$t/manifest.hl" ] && basename "$t"; done; done | sort -u`]
    stdout: StdioCollector {
      onStreamFinished: root._cursorThemes = text.split("\n").filter(name => name !== "")
    }
  }

  Process {
    id: startWallpaperDaemon
    command: ["sh", "-c", "command -v awww-daemon >/dev/null || exit 0; awww query >/dev/null 2>&1 || setsid -f awww-daemon >/dev/null 2>&1"]
  }
}
