#!/usr/bin/env bash
#
# Description: Makes <dir>/hyprland.lua axiom's for the "managed" Hyprland
#              mode (HyprlandConfigManager), or says what that would do.
# Usage:       claim_hyprland.sh check <dir> <header>
#              claim_hyprland.sh claim <dir> <header>
#              header: the first line prefix of a file axiom wrote
#              ("-- Generated by axiom"). Prints one word:
#                ours     the file is already axiom's
#                blocked:link       <dir> or its hyprland.lua is a symlink
#                blocked:git:<repo> <dir> is in the git repository <repo>
#                         either way never taken over
#                adopt    (check) an existing hyprland.lua would be moved
#                stock    (check) hyprland.lua is Hyprland's example config
#                         ($AXIOM_HYPR_EXAMPLE, /usr/share/hypr/hyprland.lua),
#                         as is or as Hyprland autogenerates it, maybe with
#                         the autostart line install.sh adds:
#                         it would only be backed up, since its binds and
#                         monitor rule would fight axiom's
#                new      (check) there's no hyprland.lua yet
#                adopted:<name>  (claim) done: user/ exists, and the
#                         existing hyprland.lua is now user/<name>
#                         (00-previous.lua, or 00-previous-<date>.lua when
#                         that's taken), with a dated copy beside the
#                         original path. Its lines that start axiom or load
#                         its included module are commented out: axiom's
#                         hyprland.lua does both now, and a second start
#                         without -n would be a second shell
#                created  (claim) done: user/ exists; there was no
#                         hyprland.lua
#                replaced (claim) done: user/ exists, and the example
#                         config is only kept as the dated copy
#              Writes nothing on check, ours or blocked.

set -uo pipefail

action=${1:-}
dir=${2:-}
header=${3:-}
example=${AXIOM_HYPR_EXAMPLE:-/usr/share/hypr/hyprland.lua}
if [[ "$action" != "check" && "$action" != "claim" ]] || [[ -z "$dir" || -z "$header" ]]; then
  echo "Usage: $0 check|claim <dir> <header>" >&2
  exit 2
fi
dir=${dir%/}
file=$dir/hyprland.lua

if [[ -f "$file" ]] && [[ "$(head -n 1 "$file")" == "$header"* ]]; then
  echo ours
  exit 0
fi
if [[ -L "$dir" || -L "$file" ]]; then
  echo blocked:link
  exit 0
fi
if repo=$(git -C "$dir" rev-parse --show-toplevel 2>/dev/null); then
  echo "blocked:git:$repo"
  exit 0
fi

# The example config, give or take whitespace, blank lines and the line
# that starts axiom (install.sh's, marked "-- axiom"). A config Hyprland
# generated itself (with no hyprland.lua at its first start) is the example
# too: it adds a banner and an `autogenerated` line, and picks the `menu`
# launcher by what's installed
stock_lines() {
  grep -vE '(qs|quickshell) .*axiom.*-- axiom[[:space:]]*$|^-- (-- )+--[[:space:]]*$|^-- AUTOGENERATED HYPRLAND CONFIG\.|^-- EDIT THIS CONFIG ACCORDING TO THE WIKI|^hl\.config\(\{ *autogenerated *= *true *\}\)|^local menu +=' "$1"
}
is_stock() {
  [[ -f "$example" ]] && diff -qbB <(stock_lines "$file") <(stock_lines "$example") >/dev/null 2>&1
}

# Comments out the lines that start axiom (install.sh's, the Hyprland
# page's, any `qs … -c axiom`) or load its included module, unless that
# leaves the file unparsable (then it stays as it is)
disable_axiom_lines() {
  local target=$1 edited
  edited=$(mktemp) || return 0
  sed -E \
    -e '/^[[:space:]]*--/b' \
    -e '/(qs|quickshell) .*(-c +['"'"'"]?axiom|-p +['"'"'"]?[^[:space:]]*axiom)|dofile.*axiom\/hyprland\.lua|axiom\.setup\(/s/^/-- (axiom starts and loads itself now) /' \
    "$target" >"$edited"
  if luac -p "$edited" >/dev/null 2>&1; then
    cat "$edited" >"$target"
  fi
  rm -f "$edited"
}

if [[ "$action" == "check" ]]; then
  if [[ ! -f "$file" ]]; then
    echo new
  elif is_stock; then
    echo stock
  else
    echo adopt
  fi
  exit 0
fi

mkdir -p "$dir/user" || exit 1
if [[ -f "$file" ]]; then
  backup="$file.axiom-backup-$(date +%Y%m%d-%H%M%S)"
  if is_stock; then
    mv "$file" "$backup" || exit 1
    echo replaced
    exit 0
  fi
  name=00-previous.lua
  [[ -e "$dir/user/$name" ]] && name=00-previous-$(date +%Y%m%d-%H%M%S).lua
  cp -p "$file" "$backup" && mv "$file" "$dir/user/$name" || exit 1
  disable_axiom_lines "$dir/user/$name"
  echo "adopted:$name"
  exit 0
fi
echo created
